/* ===========================================================
   PRODUCTS — data + rendering helpers
   Embedded for offline file:// usage (no fetch required).
   =========================================================== */

const PRODUCTS = [
  { id: 1, name: "PainAway Rapid Relief Tablets", brand: "PainAway", category: "Pain Relief", price: 149, oldPrice: 199, rating: 4.6, reviews: 214, stock: "in", stockLabel: "In Stock", badge: "-25%", icon: "capsule", prescriptionRequired: false, deliveryDays: 1, manufacturer: "Surya Pharma Ltd.", expiry: "Mar 2028", ingredients: "Ibuprofen 200mg, Paracetamol 325mg", benefits: "Fast headache relief,Reduces body pain,Non-drowsy formula", howToUse: "Take 1 tablet after meals, up to 3 times daily. Do not exceed recommended dose.", warnings: "Avoid if allergic to NSAIDs. Not for children under 12. Consult doctor if pregnant.", desc: "Fast-acting relief from headaches, body ache, and mild fever. Non-drowsy formula suitable for daily use as directed.", bestSeller: true, featured: true },
  { id: 2, name: "FlexoJoint Muscle Gel", brand: "FlexoJoint", category: "Pain Relief", price: 220, oldPrice: 260, rating: 4.4, reviews: 132, stock: "in", stockLabel: "In Stock", badge: "-15%", icon: "tube", prescriptionRequired: false, deliveryDays: 1, manufacturer: "LifeWell Labs", expiry: "Jun 2028", ingredients: "Diclofenac Diethylamine 1.16%, Menthol, Methyl Salicylate", benefits: "Soothes muscle pain,Cooling sensation,Non-greasy formula", howToUse: "Apply a thin layer to affected area 3-4 times daily. Massage gently.", warnings: "For external use only. Avoid contact with eyes, mouth, and open wounds.", desc: "Soothing topical gel for joint and muscle pain, with a cooling effect that absorbs quickly without greasy residue.", bestSeller: false, featured: true },
  { id: 3, name: "ColdShield Cough Syrup", brand: "ColdShield", category: "Cold & Flu", price: 95, oldPrice: 120, rating: 4.5, reviews: 189, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "bottle", prescriptionRequired: false, deliveryDays: 1, manufacturer: "MedLife Pharma", expiry: "Sep 2027", ingredients: "Dextromethorphan 10mg/5ml, Guaifenesin 100mg/5ml", benefits: "Eases dry cough,Reduces throat irritation,Family-friendly formula", howToUse: "Adults: 10ml every 4-6 hours. Children 6-12: 5ml. Shake well before use.", warnings: "May cause drowsiness. Do not drive after use. Not for infants under 2.", desc: "A gentle syrup that eases cough, throat irritation, and nasal congestion for the whole family.", bestSeller: true, featured: true },
  { id: 4, name: "FluCare Combo Tablets", brand: "FluCare", category: "Cold & Flu", price: 130, oldPrice: 150, rating: 4.3, reviews: 97, stock: "low", stockLabel: "Only 4 left", badge: "", icon: "capsule", prescriptionRequired: false, deliveryDays: 2, manufacturer: "Surya Pharma Ltd.", expiry: "Dec 2027", ingredients: "Paracetamol 500mg, Phenylephrine 5mg, Cetirizine 5mg", benefits: "Relieves fever,Clears nasal congestion,Reduces body ache", howToUse: "Take 1 tablet twice daily after meals. Do not exceed 4 tablets in 24 hours.", warnings: "May cause drowsiness. Consult doctor if symptoms persist beyond 5 days.", desc: "Combination formula targeting fever, body ache, and congestion associated with common flu.", bestSeller: false, featured: false },
  { id: 5, name: "VitaBoost Multivitamin", brand: "VitaBoost", category: "Vitamins", price: 349, oldPrice: 449, rating: 4.8, reviews: 341, stock: "in", stockLabel: "In Stock", badge: "-22%", icon: "jar", prescriptionRequired: false, deliveryDays: 1, manufacturer: "NutraWell Inc.", expiry: "Jul 2028", ingredients: "Vitamin A, B-Complex, C, D3, E, K, Zinc, Iron, Calcium, Magnesium", benefits: "Boosts energy,Strengthens immunity,Supports bone health,Improves skin quality", howToUse: "Take 1 tablet daily with breakfast. Best taken consistently for 3+ months.", warnings: "Keep out of reach of children. Store in a cool dry place.", desc: "Daily multivitamin with 24 essential nutrients to support energy, immunity, and overall wellness.", bestSeller: true, featured: true },
  { id: 6, name: "Vitamin D3 Sunshine Drops", brand: "VitaBoost", category: "Vitamins", price: 210, oldPrice: 250, rating: 4.7, reviews: 176, stock: "in", stockLabel: "In Stock", badge: "-16%", icon: "dropper", prescriptionRequired: false, deliveryDays: 1, manufacturer: "NutraWell Inc.", expiry: "Oct 2028", ingredients: "Cholecalciferol (Vitamin D3) 1000 IU per drop, MCT Oil", benefits: "Supports bone density,Boosts immunity,Easy to absorb,Suitable for all ages", howToUse: "Add 2 drops to food or water daily. Can be taken with or without meals.", warnings: "Do not exceed recommended dose. Consult doctor if taking blood thinners.", desc: "Concentrated D3 drops to support bone health and immunity, ideal for the whole family.", bestSeller: false, featured: true },
  { id: 7, name: "GlucoBalance Care Tablets", brand: "GlucoBalance", category: "Diabetes Care", price: 410, oldPrice: 480, rating: 4.5, reviews: 88, stock: "in", stockLabel: "In Stock", badge: "-15%", icon: "capsule", prescriptionRequired: true, deliveryDays: 2, manufacturer: "DiaCare Labs", expiry: "May 2028", ingredients: "Metformin 500mg extended-release", benefits: "Regulates blood sugar,Extended release formula,Well-tolerated", howToUse: "Take as directed by physician. Usually 1 tablet twice daily with meals.", warnings: "Prescription required. Regular blood sugar monitoring recommended.", desc: "Supports healthy blood sugar levels as part of a balanced diabetes management routine.", bestSeller: false, featured: true },
  { id: 8, name: "SugarCheck Glucometer Kit", brand: "SugarCheck", category: "Diabetes Care", price: 899, oldPrice: 1099, rating: 4.6, reviews: 152, stock: "in", stockLabel: "In Stock", badge: "-18%", icon: "device", prescriptionRequired: false, deliveryDays: 1, manufacturer: "MedTech Devices", expiry: "N/A", ingredients: "N/A", benefits: "5-second results,25 test strips included,Compact and portable,Memory for 500 readings", howToUse: "Insert strip, apply blood drop, read result in 5 seconds. See manual for details.", warnings: "For external diagnostic use. Strips are single-use only.", desc: "Accurate, easy-to-use glucometer kit with 25 test strips and lancets included.", bestSeller: true, featured: true },
  { id: 9, name: "CardioPlus Omega-3 Softgels", brand: "CardioPlus", category: "Heart Care", price: 380, oldPrice: 430, rating: 4.7, reviews: 203, stock: "in", stockLabel: "In Stock", badge: "-12%", icon: "capsule", prescriptionRequired: false, deliveryDays: 1, manufacturer: "HeartWell Labs", expiry: "Aug 2028", ingredients: "EPA 360mg, DHA 240mg per softgel, Vitamin E 10mg", benefits: "Supports heart health,Lowers triglycerides,Anti-inflammatory,Brain health support", howToUse: "Take 1 softgel daily with meals. Best with dinner for optimal absorption.", warnings: "Consult doctor if taking blood thinners. Contains fish-derived ingredients.", desc: "High-purity fish oil softgels supporting healthy cholesterol levels and heart function.", bestSeller: true, featured: true },
  { id: 10, name: "PressureEase BP Monitor", brand: "PressureEase", category: "Heart Care", price: 1450, oldPrice: 1700, rating: 4.8, reviews: 264, stock: "low", stockLabel: "Only 3 left", badge: "-15%", icon: "device", prescriptionRequired: false, deliveryDays: 2, manufacturer: "MedTech Devices", expiry: "N/A", ingredients: "N/A", benefits: "Clinical accuracy,Irregular heartbeat detection,120-reading memory,Large LCD display", howToUse: "Sit quietly for 5 minutes before measuring. Wrap cuff around left arm, press start.", warnings: "Not a substitute for professional medical advice. Compare with clinical readings.", desc: "Clinically validated digital blood pressure monitor with irregular heartbeat detection.", bestSeller: false, featured: false },
  { id: 11, name: "DermaPure Gentle Face Wash", brand: "DermaPure", category: "Skin Care", price: 175, oldPrice: 210, rating: 4.4, reviews: 118, stock: "in", stockLabel: "In Stock", badge: "-17%", icon: "bottle", prescriptionRequired: false, deliveryDays: 1, manufacturer: "SkinFirst Labs", expiry: "Apr 2028", ingredients: "Niacinamide 2%, Salicylic Acid 0.5%, Aloe Vera Extract", benefits: "Gentle cleansing,Acne prevention,Non-drying formula,pH balanced", howToUse: "Wet face, apply a small amount, massage gently, rinse with water. Use twice daily.", warnings: "Avoid contact with eyes. Discontinue if irritation occurs.", desc: "Dermatologist-tested gentle cleanser suitable for sensitive and acne-prone skin.", bestSeller: false, featured: true },
  { id: 12, name: "SoftGlow Moisturizing Cream", brand: "SoftGlow", category: "Skin Care", price: 260, oldPrice: 310, rating: 4.6, reviews: 145, stock: "in", stockLabel: "In Stock", badge: "-16%", icon: "jar", prescriptionRequired: false, deliveryDays: 1, manufacturer: "SkinFirst Labs", expiry: "Feb 2028", ingredients: "Ceramides, Hyaluronic Acid, Shea Butter, Vitamin E", benefits: "24-hour hydration,Strengthens skin barrier,Non-comedogenic,Fragrance-free", howToUse: "Apply generously to clean face and body, morning and evening.", warnings: "For external use only. Patch test recommended for sensitive skin.", desc: "24-hour hydration cream with ceramides to strengthen and soothe dry skin.", bestSeller: true, featured: false },
  { id: 13, name: "LittleSteps Baby Lotion", brand: "LittleSteps", category: "Baby Care", price: 199, oldPrice: 230, rating: 4.7, reviews: 231, stock: "in", stockLabel: "In Stock", badge: "-13%", icon: "bottle", prescriptionRequired: false, deliveryDays: 1, manufacturer: "BabySoft Care", expiry: "Nov 2027", ingredients: "Oat Extract, Dimethicone, Glycerin, Coconut Oil", benefits: "Tear-free formula,24-hour moisture,Hypoallergenic,Pediatrician tested", howToUse: "Apply gently all over baby's body after bath. Suitable from newborn.", warnings: "Keep out of reach of children. External use only.", desc: "Mild, tear-free lotion formulated for delicate newborn and infant skin.", bestSeller: true, featured: true },
  { id: 14, name: "GentleCare Diaper Rash Cream", brand: "GentleCare", category: "Baby Care", price: 165, oldPrice: 190, rating: 4.5, reviews: 97, stock: "in", stockLabel: "In Stock", badge: "-13%", icon: "jar", prescriptionRequired: false, deliveryDays: 1, manufacturer: "BabySoft Care", expiry: "Jan 2028", ingredients: "Zinc Oxide 15%, Dimethicone 1%, Aloe Vera", benefits: "Heals rashes fast,Forms protective barrier,Soothes irritation,Pediatrician recommended", howToUse: "Apply at every diaper change, especially at bedtime or when exposed to wet diapers.", warnings: "For external use only. If rash persists beyond 7 days, consult pediatrician.", desc: "Soothing barrier cream that helps protect and heal delicate baby skin.", bestSeller: false, featured: false },
  { id: 15, name: "FreshDay Hand Sanitizer", brand: "FreshDay", category: "Personal Care", price: 85, oldPrice: 100, rating: 4.3, reviews: 302, stock: "in", stockLabel: "In Stock", badge: "-15%", icon: "bottle", prescriptionRequired: false, deliveryDays: 1, manufacturer: "CleanPure Industries", expiry: "Jun 2027", ingredients: "Ethyl Alcohol 70%, Aloe Vera Gel, Vitamin E", benefits: "Kills 99.9% germs,Non-sticky,Moisturizes hands,Pocket-friendly", howToUse: "Apply a coin-sized amount to palms. Rub hands together until dry.", warnings: "Flammable. Keep away from heat. For external use only.", desc: "70% alcohol-based sanitizer that kills 99.9% of germs while keeping hands soft.", bestSeller: true, featured: false },
  { id: 16, name: "OralFresh Antiseptic Mouthwash", brand: "OralFresh", category: "Personal Care", price: 120, oldPrice: 145, rating: 4.4, reviews: 168, stock: "in", stockLabel: "In Stock", badge: "-17%", icon: "bottle", prescriptionRequired: false, deliveryDays: 1, manufacturer: "DentalCare Co.", expiry: "Aug 2027", ingredients: "Cetylpyridinium Chloride 0.05%, Menthol, Fluoride", benefits: "12-hour fresh breath,Fights plaque bacteria,Alcohol-free,Strengthens enamel", howToUse: "Rinse with 20ml for 30 seconds after brushing. Do not swallow.", warnings: "Not for children under 6. Do not swallow. Seek medical advice if swallowed.", desc: "Alcohol-free mouthwash that fights plaque and freshens breath for up to 12 hours.", bestSeller: false, featured: false },
  { id: 17, name: "ComfortFlex Knee Support", brand: "ComfortFlex", category: "Orthopedic", price: 450, oldPrice: 550, rating: 4.5, reviews: 76, stock: "in", stockLabel: "In Stock", badge: "-18%", icon: "device", prescriptionRequired: false, deliveryDays: 2, manufacturer: "OrthoLife Medical", expiry: "N/A", ingredients: "N/A", benefits: "Breathable compression,Pain relief,Stabilizes joint,Unisex design", howToUse: "Slide over knee ensuring patella opening aligns. Adjust straps for comfort.", warnings: "Not for use over open wounds. Discontinue if numbness or increased pain.", desc: "Breathable compression knee support for pain relief during daily activity.", bestSeller: false, featured: false },
  { id: 18, name: "PulseOx Fingertip Oximeter", brand: "PulseOx", category: "Medical Equipment", price: 799, oldPrice: 950, rating: 4.7, reviews: 289, stock: "in", stockLabel: "In Stock", badge: "-16%", icon: "device", prescriptionRequired: false, deliveryDays: 1, manufacturer: "MedTech Devices", expiry: "N/A", ingredients: "N/A", benefits: "Fast SpO2 reading,Pulse rate monitor,OLED display,Auto power-off", howToUse: "Insert finger into device, press power button, wait 8 seconds for reading.", warnings: "For general wellness, not a diagnostic device. Consult doctor for medical decisions.", desc: "Fast, accurate SpO2 and pulse rate readings with a bright digital display.", bestSeller: true, featured: true },
  { id: 19, name: "N95 ProShield Face Masks (10)", brand: "ProShield", category: "Medical Equipment", price: 299, oldPrice: 350, rating: 4.6, reviews: 412, stock: "in", stockLabel: "In Stock", badge: "-15%", icon: "device", prescriptionRequired: false, deliveryDays: 1, manufacturer: "SafeGuard PPE", expiry: "N/A", ingredients: "N/A", benefits: "5-layer filtration,BFE ≥95%,Nose clip for fit,Individually packed", howToUse: "Place over nose and mouth, adjust nose clip, secure ear loops.", warnings: "Single use. Discard after 8 hours or when damp. Not for children under 3.", desc: "5-layer protective face masks offering a secure, breathable fit for everyday use.", bestSeller: true, featured: false },
  { id: 20, name: "ImmunoGuard Vitamin C Chewables", brand: "ImmunoGuard", category: "Vitamins", price: 240, oldPrice: 280, rating: 4.6, reviews: 198, stock: "out", stockLabel: "Out of Stock", badge: "", icon: "jar", prescriptionRequired: false, deliveryDays: 3, manufacturer: "NutraWell Inc.", expiry: "May 2027", ingredients: "Vitamin C 500mg (as Ascorbic Acid), Natural Orange Flavor", benefits: "Immune support,Antioxidant,Pleasant taste,Easy to chew", howToUse: "Chew 1 tablet daily. Can be taken with or without food.", warnings: "Do not exceed recommended dose. Excess may cause gastric discomfort.", desc: "Tangy orange-flavoured chewable tablets to support daily immune health.", bestSeller: false, featured: true },
  { id: 21, name: "OrthoRelief Back Support Belt", brand: "OrthoRelief", category: "Orthopedic", price: 680, oldPrice: 850, rating: 4.5, reviews: 134, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "device", prescriptionRequired: false, deliveryDays: 2, manufacturer: "OrthoLife Medical", expiry: "N/A", ingredients: "N/A", benefits: "Lumbar support,Adjustable compression,Breathable mesh,Posture correction", howToUse: "Wrap around lower back, secure velcro straps to desired compression level.", warnings: "Not for sleeping. Consult doctor for chronic back conditions.", desc: "Adjustable lumbar support belt for lower back pain relief and posture improvement.", bestSeller: true, featured: true },
  { id: 22, name: "CalciFlex Calcium + D3", brand: "CalciFlex", category: "Orthopedic", price: 320, oldPrice: 399, rating: 4.6, reviews: 187, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "capsule", prescriptionRequired: false, deliveryDays: 1, manufacturer: "BoneHealth Labs", expiry: "Sep 2028", ingredients: "Calcium Carbonate 500mg, Vitamin D3 250 IU, Magnesium 100mg", benefits: "Strengthens bones,Prevents osteoporosis,Supports joint health,Easy absorption", howToUse: "Take 1 tablet twice daily with meals.", warnings: "Consult doctor if on heart medication. Not for children under 12.", desc: "Essential calcium and vitamin D3 supplement for strong bones and joint health.", bestSeller: false, featured: true },
  { id: 23, name: "FemWell Iron + Folic Acid", brand: "FemWell", category: "Women's Health", price: 280, oldPrice: 350, rating: 4.7, reviews: 256, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "capsule", prescriptionRequired: false, deliveryDays: 1, manufacturer: "WomenCare Labs", expiry: "Nov 2028", ingredients: "Ferrous Fumarate 150mg, Folic Acid 500mcg, Vitamin B12 5mcg", benefits: "Prevents anemia,Supports pregnancy,Boosts energy,Essential for women", howToUse: "Take 1 tablet daily, preferably on empty stomach with vitamin C for better absorption.", warnings: "May cause constipation. Take 2 hours apart from tea/coffee/calcium.", desc: "Comprehensive iron and folic acid supplement designed for women's unique nutritional needs.", bestSeller: true, featured: true },
  { id: 24, name: "FemCare Intimate Wash", brand: "FemCare", category: "Women's Health", price: 195, oldPrice: 245, rating: 4.5, reviews: 178, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "bottle", prescriptionRequired: false, deliveryDays: 1, manufacturer: "WomenCare Labs", expiry: "Jul 2028", ingredients: "Lactic Acid, Tea Tree Oil, Aloe Vera, pH 3.5 balanced", benefits: "pH balanced,Prevents infections,Gentle formula,Dermatologist tested", howToUse: "Use a small amount with water for external intimate area cleansing during bath.", warnings: "External use only. Discontinue if irritation occurs.", desc: "Gentle, pH-balanced intimate wash with tea tree oil for daily feminine hygiene.", bestSeller: false, featured: false },
  { id: 25, name: "ManForce Multivitamin Pro", brand: "ManForce", category: "Men's Health", price: 399, oldPrice: 499, rating: 4.6, reviews: 312, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "jar", prescriptionRequired: false, deliveryDays: 1, manufacturer: "ActiveMan Labs", expiry: "Dec 2028", ingredients: "Zinc 15mg, Vitamin D3 1000IU, B-Complex, Ashwagandha 300mg, Lycopene 4mg", benefits: "Boosts stamina,Muscle recovery,Immune support,Prostate health", howToUse: "Take 1 tablet daily with breakfast for best results.", warnings: "Not for women or children. Consult doctor if on medication.", desc: "Advanced multivitamin formulated for active men with ashwagandha and zinc for vitality.", bestSeller: true, featured: true },
  { id: 26, name: "ProstaGuard Health Capsules", brand: "ProstaGuard", category: "Men's Health", price: 520, oldPrice: 650, rating: 4.4, reviews: 89, stock: "in", stockLabel: "In Stock", badge: "-20%", icon: "capsule", prescriptionRequired: false, deliveryDays: 2, manufacturer: "ActiveMan Labs", expiry: "Oct 2028", ingredients: "Saw Palmetto 320mg, Beta-Sitosterol, Zinc 10mg, Selenium 55mcg", benefits: "Prostate health,Urinary comfort,Natural formula,Clinically studied", howToUse: "Take 1 capsule twice daily with meals. Best results after 8 weeks.", warnings: "Consult doctor before use, especially if on blood thinners.", desc: "Natural prostate support formula with saw palmetto for urinary and reproductive health.", bestSeller: false, featured: false },
  { id: 27, name: "AllerShield Antihistamine", brand: "AllerShield", category: "Cold & Flu", price: 110, oldPrice: 140, rating: 4.4, reviews: 156, stock: "in", stockLabel: "In Stock", badge: "-21%", icon: "capsule", prescriptionRequired: false, deliveryDays: 1, manufacturer: "MedLife Pharma", expiry: "Mar 2028", ingredients: "Cetirizine Hydrochloride 10mg", benefits: "24-hour allergy relief,Non-drowsy,Fast acting,Treats sneezing and itching", howToUse: "Take 1 tablet daily, with or without food. Best taken in the evening.", warnings: "May cause mild drowsiness in some individuals. Avoid alcohol.", desc: "24-hour non-drowsy antihistamine for seasonal allergies, sneezing, and itchy eyes.", bestSeller: false, featured: false },
  { id: 28, name: "GlucoStrips Test Strips (50)", brand: "SugarCheck", category: "Diabetes Care", price: 540, oldPrice: 650, rating: 4.5, reviews: 198, stock: "in", stockLabel: "In Stock", badge: "-17%", icon: "device", prescriptionRequired: false, deliveryDays: 1, manufacturer: "MedTech Devices", expiry: "Feb 2027", ingredients: "N/A", benefits: "Compatible with SugarCheck meter,Accurate readings,Easy to use,Bulk pack", howToUse: "Insert strip into meter, apply blood sample to test area. Result in 5 seconds.", warnings: "Single use only. Store in original vial. Discard after expiry date.", desc: "50-count test strip refill pack compatible with SugarCheck glucometer for accurate blood sugar monitoring.", bestSeller: false, featured: false },
  { id: 29, name: "NeuralCalm Sleep Aid", brand: "NeuralCalm", category: "Personal Care", price: 310, oldPrice: 399, rating: 4.3, reviews: 124, stock: "in", stockLabel: "In Stock", badge: "-22%", icon: "jar", prescriptionRequired: false, deliveryDays: 1, manufacturer: "MindWell Labs", expiry: "Jan 2028", ingredients: "Melatonin 3mg, Valerian Root 200mg, L-Theanine 100mg, Chamomile", benefits: "Natural sleep support,Non-habit forming,Relaxation,Wake refreshed", howToUse: "Take 1 capsule 30 minutes before bedtime. Do not exceed 1 capsule.", warnings: "Do not drive after taking. Not for pregnant/nursing women. Consult doctor if on medication.", desc: "Natural sleep support supplement with melatonin and calming herbs for restful nights.", bestSeller: false, featured: false },
  { id: 30, name: "AquaPure Water Purifier Tablets", brand: "AquaPure", category: "Personal Care", price: 65, oldPrice: 80, rating: 4.2, reviews: 87, stock: "in", stockLabel: "In Stock", badge: "-19%", icon: "jar", prescriptionRequired: false, deliveryDays: 1, manufacturer: "CleanPure Industries", expiry: "Dec 2027", ingredients: "Sodium Dichloroisocyanurate 8.5mg per tablet", benefits: "Purifies 1L per tablet,Kills bacteria & viruses,Travel-friendly,No taste", howToUse: "Drop 1 tablet in 1L water, wait 30 minutes before drinking.", warnings: "For emergency water purification. Not a replacement for filtered water.", desc: "Portable water purification tablets for safe drinking water anywhere.", bestSeller: false, featured: false },
  { id: 31, name: "ElastoGrip Wrist Brace", brand: "ElastoGrip", category: "Orthopedic", price: 350, oldPrice: 420, rating: 4.4, reviews: 92, stock: "in", stockLabel: "In Stock", badge: "-17%", icon: "device", prescriptionRequired: false, deliveryDays: 2, manufacturer: "OrthoLife Medical", expiry: "N/A", ingredients: "N/A", benefits: "Carpal tunnel relief,Adjustable support,Breathable fabric,Unisex", howToUse: "Slide onto wrist, adjust straps. Wear during activity or as directed by physician.", warnings: "Remove if numbness occurs. Not for use over broken skin.", desc: "Ergonomic wrist brace for carpal tunnel syndrome, sprains, and repetitive strain injury.", bestSeller: false, featured: false },
  { id: 32, name: "SkinShield SPF 50 Sunscreen", brand: "DermaPure", category: "Skin Care", price: 295, oldPrice: 380, rating: 4.5, reviews: 203, stock: "in", stockLabel: "In Stock", badge: "-22%", icon: "tube", prescriptionRequired: false, deliveryDays: 1, manufacturer: "SkinFirst Labs", expiry: "Mar 2028", ingredients: "Zinc Oxide 8%, Titanium Dioxide 4%, Hyaluronic Acid, Vitamin E", benefits: "Broad spectrum UVA/UVB,Lightweight,Non-greasy,Moisturizing", howToUse: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours.", warnings: "For external use only. Avoid contact with eyes.", desc: "Lightweight, non-greasy SPF 50 sunscreen with hydrating formula for daily sun protection.", bestSeller: true, featured: false }
];

const CATEGORY_ICONS = {
  "Pain Relief": "pill", "Cold & Flu": "flu", "Vitamins": "leaf", "Diabetes Care": "drop",
  "Heart Care": "heart", "Skin Care": "sparkle", "Baby Care": "baby", "Personal Care": "shield",
  "Medical Equipment": "device", "Orthopedic": "bone", "Women's Health": "female", "Men's Health": "male"
};

const CATEGORY_DESC = {
  "Pain Relief": "Tablets, gels & sprays for headaches, muscle aches and joint pain.",
  "Cold & Flu": "Syrups, tablets & lozenges for cough, cold, and seasonal allergies.",
  "Vitamins": "Multivitamins, supplements & nutrition for daily wellness.",
  "Diabetes Care": "Glucometers, strips, supplements & diabetes management essentials.",
  "Heart Care": "Omega-3, BP monitors & heart-healthy supplements.",
  "Skin Care": "Face washes, creams, sunscreens & derma-tested solutions.",
  "Baby Care": "Lotions, rash creams & gentle care for your little one.",
  "Personal Care": "Sanitizers, mouthwash, hygiene & everyday wellness.",
  "Medical Equipment": "Oximeters, masks, thermometers & home health devices.",
  "Orthopedic": "Knee supports, back belts, wrist braces & bone supplements.",
  "Women's Health": "Iron, folic acid, intimate care & women's wellness.",
  "Men's Health": "Multivitamins, prostate care & men's vitality products."
};

/* ---------- Helpers ---------- */
function getProductById(id) { return PRODUCTS.find(p => p.id === Number(id)); }
function getProductsByCategory(cat) { return PRODUCTS.filter(p => p.category === cat); }
function formatPrice(n) { return "₹" + Number(n).toLocaleString("en-IN"); }

/* ---------- SVG icon library (medical themed, inline, no external assets) ---------- */
function productIconSVG(type) {
  const icons = {
    capsule: `<svg viewBox="0 0 100 100" fill="none"><rect x="20" y="38" width="60" height="24" rx="12" fill="var(--green)" opacity=".18"/><g><rect x="18" y="40" width="30" height="20" rx="10" fill="var(--blue)"/><rect x="48" y="40" width="30" height="20" rx="10" fill="var(--green)"/></g></svg>`,
    tube: `<svg viewBox="0 0 100 100" fill="none"><rect x="30" y="20" width="40" height="60" rx="10" fill="var(--green)" opacity=".85"/><rect x="38" y="12" width="24" height="14" rx="4" fill="var(--blue)"/><rect x="34" y="55" width="32" height="6" rx="3" fill="#fff" opacity=".6"/><rect x="34" y="65" width="24" height="5" rx="2.5" fill="#fff" opacity=".4"/></svg>`,
    bottle: `<svg viewBox="0 0 100 100" fill="none"><rect x="32" y="10" width="16" height="12" rx="2" fill="var(--blue-dark)"/><path d="M28 24 h24 a6 6 0 0 1 6 6 v50 a6 6 0 0 1 -6 6 h-24 a6 6 0 0 1 -6 -6 v-50 a6 6 0 0 1 6 -6 z" fill="var(--blue)"/><rect x="24" y="45" width="32" height="26" rx="4" fill="#fff" opacity=".85"/><path d="M40 51 v14 M33 58 h14" stroke="var(--green)" stroke-width="4" stroke-linecap="round"/></svg>`,
    jar: `<svg viewBox="0 0 100 100" fill="none"><rect x="28" y="30" width="44" height="46" rx="10" fill="var(--green)"/><rect x="24" y="20" width="52" height="14" rx="6" fill="var(--green-dark)"/><circle cx="50" cy="53" r="12" fill="#fff" opacity=".9"/><path d="M50 47 v12 M44 53 h12" stroke="var(--blue)" stroke-width="3.5" stroke-linecap="round"/></svg>`,
    dropper: `<svg viewBox="0 0 100 100" fill="none"><rect x="42" y="14" width="16" height="30" rx="6" fill="var(--blue)"/><path d="M42 44 h16 l-6 34 a4 4 0 0 1 -4 0 z" fill="var(--green)"/><rect x="38" y="10" width="24" height="8" rx="3" fill="var(--blue-dark)"/></svg>`,
    device: `<svg viewBox="0 0 100 100" fill="none"><rect x="18" y="26" width="64" height="48" rx="10" fill="var(--blue)"/><rect x="26" y="34" width="48" height="22" rx="4" fill="#fff" opacity=".9"/><path d="M30 45 h8 l4 -8 6 16 5 -12 4 4 h11" stroke="var(--green)" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="34" cy="65" r="4" fill="#fff"/><circle cx="50" cy="65" r="4" fill="#fff" opacity=".6"/><circle cx="66" cy="65" r="4" fill="#fff" opacity=".6"/></svg>`
  };
  return icons[type] || icons.capsule;
}

function categoryIconSVG(type) {
  const s = `stroke="var(--green-dark)" stroke-width="5" fill="none" stroke-linecap="round" stroke-linejoin="round"`;
  const icons = {
    pill: `<svg viewBox="0 0 48 48"><rect x="8" y="19" width="32" height="12" rx="6" ${s}/><path d="M24 19 V31" ${s}/></svg>`,
    flu: `<svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="14" ${s}/><path d="M24 14 v6 M24 28 v6 M14 24 h6 M28 24 h6" ${s}/></svg>`,
    leaf: `<svg viewBox="0 0 48 48"><path d="M14 34 C10 20 20 10 36 10 C36 26 26 36 14 34 Z" ${s}/><path d="M16 32 L32 12" ${s}/></svg>`,
    drop: `<svg viewBox="0 0 48 48"><path d="M24 8 C30 20 36 26 36 32 a12 12 0 0 1 -24 0 C12 26 18 20 24 8 Z" ${s}/></svg>`,
    heart: `<svg viewBox="0 0 48 48"><path d="M24 38 C10 28 6 20 10 14 a9 9 0 0 1 14 -1 a9 9 0 0 1 14 1 c4 6 0 14 -14 24 Z" ${s}/><path d="M14 24 h6 l3 -6 4 10 3 -6 h6" ${s}/></svg>`,
    sparkle: `<svg viewBox="0 0 48 48"><path d="M24 8 L27 20 L39 24 L27 28 L24 40 L21 28 L9 24 L21 20 Z" ${s}/></svg>`,
    baby: `<svg viewBox="0 0 48 48"><circle cx="24" cy="18" r="9" ${s}/><path d="M11 40 C11 28 37 28 37 40" ${s}/></svg>`,
    shield: `<svg viewBox="0 0 48 48"><path d="M24 6 L38 12 V22 C38 32 32 38 24 42 C16 38 10 32 10 22 V12 Z" ${s}/><path d="M18 23 l4 4 8 -9" ${s}/></svg>`,
    device: `<svg viewBox="0 0 48 48"><rect x="8" y="14" width="32" height="22" rx="4" ${s}/><path d="M13 25 h5 l3 -6 4 12 3 -9 3 3 h4" ${s}/></svg>`,
    bone: `<svg viewBox="0 0 48 48"><path d="M14 14 a5 5 0 0 1 7 0 l13 13 a5 5 0 0 1 0 7 a5 5 0 0 1 -7 0 L14 21 a5 5 0 0 1 0 -7Z" ${s}/><circle cx="14" cy="14" r="3" ${s}/><circle cx="34" cy="34" r="3" ${s}/></svg>`,
    female: `<svg viewBox="0 0 48 48"><circle cx="24" cy="18" r="10" ${s}/><path d="M24 28 v14 M18 36 h12" ${s}/></svg>`,
    male: `<svg viewBox="0 0 48 48"><circle cx="20" cy="26" r="10" ${s}/><path d="M28 18 L38 8 M30 8 h8 v8" ${s}/></svg>`
  };
  return icons[type] || icons.pill;
}

function starRow(rating) {
  const full = Math.round(rating);
  return '★★★★★'.slice(0, full) + '☆☆☆☆☆'.slice(0, 5 - full);
}

/* ---------- Card builder ---------- */
function productCardHTML(p) {
  const wished = isWishlisted(p.id);
  const stockClass = p.stock === "in" ? "in" : p.stock === "low" ? "low" : "out";
  const discountPct = p.oldPrice ? Math.round((1 - p.price / p.oldPrice) * 100) : 0;
  return `
  <article class="product-card reveal in" data-id="${p.id}" data-category="${p.category}">
    ${p.badge ? `<span class="badge">${p.badge}</span>` : (p.stock==='low' ? `<span class="badge stock-low">Low Stock</span>` : '')}
    ${p.prescriptionRequired ? `<span class="badge rx" style="left:auto;right:12px;top:12px;">℞ Rx</span>` : ''}
    <button class="wish-btn ${wished ? 'active' : ''}" aria-label="Toggle wishlist" data-wish="${p.id}">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="${wished?'currentColor':'none'}" stroke="currentColor" stroke-width="2"><path d="M12 21s-7.5-4.6-10-9.3C0.3 7.9 2.6 4 6.4 4c2 0 3.6 1 5.6 3 2-2 3.6-3 5.6-3 3.8 0 6.1 3.9 4.4 7.7C19.5 16.4 12 21 12 21z"/></svg>
    </button>
    <a href="product.html?id=${p.id}" class="product-media">${productIconSVG(p.icon)}</a>
    <div class="product-info">
      <span class="product-cat">${p.category}</span>
      <h3><a href="product.html?id=${p.id}">${p.name}</a></h3>
      <span class="product-brand">${p.brand || ''}</span>
      <div class="product-rating"><span class="stars">${starRow(p.rating)}</span> ${p.rating} (${p.reviews})</div>
      <div class="product-price">
        <span class="price-now">${formatPrice(p.price)}</span>
        ${p.oldPrice ? `<span class="price-old">${formatPrice(p.oldPrice)}</span>` : ''}
        ${discountPct ? `<span class="discount-pct">${discountPct}% off</span>` : ''}
      </div>
      <span class="stock-status ${stockClass}">${p.stockLabel}</span>
      <div class="delivery-badge">🚚 Delivery in ${p.deliveryDays || 1}-${(p.deliveryDays || 1) + 1} days</div>
      <div class="product-actions">
        <button class="btn btn-primary btn-sm" data-add="${p.id}" ${p.stock==='out'?'disabled':''}>Add to Cart</button>
        <button class="btn btn-ghost btn-sm" data-quickview="${p.id}">Quick View</button>
      </div>
    </div>
  </article>`;
}

function renderGrid(el, list, emptyMsg = "No products found. Try a different search or filter.") {
  if (!el) return;
  if (!list.length) {
    el.innerHTML = `<div class="no-results"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="var(--slate-3)" stroke-width="1.5"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/><path d="M8 11h6" stroke-linecap="round"/></svg><h3 style="margin:16px 0 8px;">No Results</h3><p>${emptyMsg}</p></div>`;
    return;
  }
  el.innerHTML = list.map(productCardHTML).join('');
}

/* ---------- Shared logo mark ---------- */
function logoSVG(size = 44) {
  return `<svg class="logo-mark" width="${size}" height="${size}" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="logoGrad" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#0F9D58"/>
        <stop offset="100%" stop-color="#1976D2"/>
      </linearGradient>
    </defs>
    <circle cx="32" cy="32" r="29" fill="none" stroke="url(#logoGrad)" stroke-width="2.4" stroke-dasharray="4 6"/>
    <circle cx="32" cy="32" r="23" fill="url(#logoGrad)"/>
    <path d="M26 22 C20 22 18 27 22 31 C26 35 30 32 26 22Z" fill="#ffffff" opacity="0.15"/>
    <path d="M24 32 h16 M32 24 v16" stroke="#ffffff" stroke-width="4.4" stroke-linecap="round"/>
    <path d="M20 40 q3 -8 8 -3" stroke="#ffffff" stroke-width="2.6" stroke-linecap="round" fill="none" opacity="0.85"/>
    <path d="M40 20 q-2 4 -4 3" stroke="#ffffff" stroke-width="1.8" stroke-linecap="round" fill="none" opacity="0.5"/>
  </svg>`;
}
